### ISSUE TITLE
Specify opening time for project

### ISSUE THREAD

**Issue by james-perretta** [eecs-autograder/autograder-server#336]
Rather than having to flip the "visible to students" box, have projects open and close automatically.

Interactions with `Project.visible_to_students`:
- When `visible_to_students` is false, the project will *not* be visible, even if the opening time has passed.
- When `visible_to_students` is true, the project will *only* be visible if the opening time has passed.

**Comment by Myrausman** [comment]
Is this issue still available or not? If its, so can I work on it.

**Comment by james-perretta** [comment]
@Myrausman, yes, this is still available! Please let me know if you have any questions as you start to work on it

**Comment by Myrausman** [comment]
I am getting issue setting up ,yesterday I was doing it with python3.10 so only 1 package was having issue I.e. backports-zoneinfo and now I tried using python3.8 but still I m getting issues of different package i.e. psycopg2
![image](https://github.com/eecs-autograder/autograder-server/assets/99428378/44158bcb-d7fa-4f5d-80b4-37614c116ab7)

**Comment by james-perretta** [comment]
Is that the full output from pip? Could you also let me know what platform
you're on?

**Comment by Myrausman** [comment]
I am using Ubuntu 22.04.3 LTS

```
(venv) myra@myra-ThinkPad-T14-Gen-2i:~/extra/autograder-server$ pip-sync requirements.txt requirements-dev.txt
Collecting certifi==2020.12.5
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting chardet==4.0.0
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting coreapi==2.3.3
  Using cached coreapi-2.3.3-py2.py3-none-any.whl (25 kB)
Collecting coreschema==0.0.4
  Using cached coreschema-0.0.4-py3-none-any.whl
Collecting django-stubs==1.8.0
  Using cached django_stubs-1.8.0-py3-none-any.whl (392 kB)
Collecting django-stubs-ext==0.2.0
  Using cached django_stubs_ext-0.2.0-py3-none-any.whl (4.6 kB)
Collecting djangorestframework-stubs==1.4.0
  Using cached djangorestframework_stubs-1.4.0-py3-none-any.whl (51 kB)
Collecting idna==2.10
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting isort==5.7.0
  Using cached isort-5.7.0-py3-none-any.whl (104 kB)
Collecting itypes==1.2.0
  Using cached itypes-1.2.0-py2.py3-none-any.whl (4.8 kB)
Collecting jinja2==2.11.3
  Using cached Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Collecting markupsafe==1.1.1
  Using cached MarkupSafe-1.1.1-cp38-cp38-manylinux2010_x86_64.whl (32 kB)
Collecting mypy==1.5.1
  Using cached mypy-1.5.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.1 MB)
Collecting mypy-extensions==1.0.0
  Using cached mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Collecting psycopg2==2.9.9
  Using cached psycopg2-2.9.9.tar.gz (384 kB)
  Preparing metadata (setup.py) ... done
Collecting pycodestyle==2.6.0
  Using cached pycodestyle-2.6.0-py2.py3-none-any.whl (41 kB)
Collecting pydocstyle==5.1.1
  Using cached pydocstyle-5.1.1-py3-none-any.whl (35 kB)
Collecting requests==2.25.1
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting snowballstemmer==2.1.0
  Using cached snowballstemmer-2.1.0-py2.py3-none-any.whl (93 kB)
Collecting typing-extensions==4.7.1
  Using cached typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Collecting urllib3==1.26.4
  Using cached urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
Requirement already satisfied: uritemplate in ./venv/lib/python3.8/site-packages (from coreapi==2.3.3->-r /tmp/tmp7ayg12k9 (line 3)) (3.0.1)
Requirement already satisfied: django in ./venv/lib/python3.8/site-packages (from django-stubs==1.8.0->-r /tmp/tmp7ayg12k9 (line 5)) (3.2.2)
Requirement already satisfied: tomli>=1.1.0 in ./venv/lib/python3.8/site-packages (from mypy==1.5.1->-r /tmp/tmp7ayg12k9 (line 13)) (2.0.1)
Requirement already satisfied: asgiref<4,>=3.3.2 in ./venv/lib/python3.8/site-packages (from django->django-stubs==1.8.0->-r /tmp/tmp7ayg12k9 (line 5)) (3.3.4)
Requirement already satisfied: pytz in ./venv/lib/python3.8/site-packages (from django->django-stubs==1.8.0->-r /tmp/tmp7ayg12k9 (line 5)) (2021.1)
Requirement already satisfied: sqlparse>=0.2.2 in ./venv/lib/python3.8/site-packages (from django->django-stubs==1.8.0->-r /tmp/tmp7ayg12k9 (line 5)) (0.4.1)
Building wheels for collected packages: psycopg2
  Building wheel for psycopg2 (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      running bdist_wheel
      running build
      running build_py
      Generating grammar tables from /usr/lib/python3.8/lib2to3/Grammar.txt
      Generating grammar tables from /usr/lib/python3.8/lib2to3/PatternGrammar.txt
      creating build
      creating build/lib.linux-x86_64-3.8
      creating build/lib.linux-x86_64-3.8/psycopg2
      copying lib/_ipaddress.py -> build/lib.linux-x86_64-3.8/psycopg2
      copying lib/pool.py -> build/lib.linux-x86_64-3.8/psycopg2
      copying lib/errors.py -> build/lib.linux-x86_64-3.8/psycopg2
      copying lib/extensions.py -> build/lib.linux-x86_64-3.8/psycopg2
      copying lib/extras.py -> build/lib.linux-x86_64-3.8/psycopg2
      copying lib/errorcodes.py -> build/lib.linux-x86_64-3.8/psycopg2
      copying lib/sql.py -> build/lib.linux-x86_64-3.8/psycopg2
      copying lib/_json.py -> build/lib.linux-x86_64-3.8/psycopg2
      copying lib/__init__.py -> build/lib.linux-x86_64-3.8/psycopg2
      copying lib/_range.py -> build/lib.linux-x86_64-3.8/psycopg2
      copying lib/tz.py -> build/lib.linux-x86_64-3.8/psycopg2
      running build_ext
      building 'psycopg2._psycopg' extension
      creating build/temp.linux-x86_64-3.8
      creating build/temp.linux-x86_64-3.8/psycopg
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPSYCOPG_VERSION=2.9.9 (dt dec pq3 ext lo64) -DPSYCOPG_DEBUG=1 -DPG_VERSION_NUM=130014 -DHAVE_LO64=1 -DPSYCOPG_DEBUG=1 -I/home/myra/extra/autograder-server/venv/include -I/usr/include/python3.8 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -I/usr/include/libxml2 -c psycopg/psycopgmodule.c -o build/temp.linux-x86_64-3.8/psycopg/psycopgmodule.o -Wdeclaration-after-statement
      In file included from psycopg/psycopgmodule.c:28:
      ./psycopg/psycopg.h:35:10: fatal error: Python.h: No such file or directory
         35 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      
      It appears you are missing some prerequisite to build the package from source.
      
      You may install a binary package by installing 'psycopg2-binary' from PyPI.
      If you want to install psycopg2 from source, please install the packages
      required for the build and try again.
      
      For further information please check the 'doc/src/install.rst' file (also at
      <https://www.psycopg.org/docs/install.html>).
      
      error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for psycopg2
  Running setup.py clean for psycopg2
Failed to build psycopg2
Installing collected packages: snowballstemmer, itypes, certifi, urllib3, typing-extensions, pydocstyle, pycodestyle, psycopg2, mypy-extensions, markupsafe, isort, idna, chardet, requests, mypy, jinja2, django-stubs-ext, django-stubs, coreschema, coreapi, djangorestframework-stubs
  Running setup.py install for psycopg2 ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for psycopg2 did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.8
      creating build/lib.linux-x86_64-3.8/psycopg2
      copying lib/_ipaddress.py -> build/lib.linux-x86_64-3.8/psycopg2
      copying lib/pool.py -> build/lib.linux-x86_64-3.8/psycopg2
      copying lib/errors.py -> build/lib.linux-x86_64-3.8/psycopg2
      copying lib/extensions.py -> build/lib.linux-x86_64-3.8/psycopg2
      copying lib/extras.py -> build/lib.linux-x86_64-3.8/psycopg2
      copying lib/errorcodes.py -> build/lib.linux-x86_64-3.8/psycopg2
      copying lib/sql.py -> build/lib.linux-x86_64-3.8/psycopg2
      copying lib/_json.py -> build/lib.linux-x86_64-3.8/psycopg2
      copying lib/__init__.py -> build/lib.linux-x86_64-3.8/psycopg2
      copying lib/_range.py -> build/lib.linux-x86_64-3.8/psycopg2
      copying lib/tz.py -> build/lib.linux-x86_64-3.8/psycopg2
      running build_ext
      building 'psycopg2._psycopg' extension
      creating build/temp.linux-x86_64-3.8
      creating build/temp.linux-x86_64-3.8/psycopg
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPSYCOPG_VERSION=2.9.9 (dt dec pq3 ext lo64) -DPSYCOPG_DEBUG=1 -DPG_VERSION_NUM=130014 -DHAVE_LO64=1 -DPSYCOPG_DEBUG=1 -I/home/myra/extra/autograder-server/venv/include -I/usr/include/python3.8 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -I/usr/include/libxml2 -c psycopg/psycopgmodule.c -o build/temp.linux-x86_64-3.8/psycopg/psycopgmodule.o -Wdeclaration-after-statement
      In file included from psycopg/psycopgmodule.c:28:
      ./psycopg/psycopg.h:35:10: fatal error: Python.h: No such file or directory
         35 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      
      It appears you are missing some prerequisite to build the package from source.
      
      You may install a binary package by installing 'psycopg2-binary' from PyPI.
      If you want to install psycopg2 from source, please install the packages
      required for the build and try again.
      
      For further information please check the 'doc/src/install.rst' file (also at
      <https://www.psycopg.org/docs/install.html>).
      
      error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> psycopg2

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
WARNING: There was an error checking the latest version of pip.
Traceback (most recent call last):
  File "/home/myra/extra/autograder-server/venv/bin/pip-sync", line 8, in <module>
    sys.exit(cli())
  File "/home/myra/extra/autograder-server/venv/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/myra/extra/autograder-server/venv/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/myra/extra/autograder-server/venv/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/myra/extra/autograder-server/venv/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/myra/extra/autograder-server/venv/lib/python3.8/site-packages/piptools/scripts/sync.py", line 145, in cli
    sync.sync(
  File "/home/myra/extra/autograder-server/venv/lib/python3.8/site-packages/piptools/sync.py", line 263, in sync
    run(  # nosec
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/myra/extra/autograder-server/venv/bin/python3.8', '-m', 'pip', 'install', '-r', '/tmp/tmp7ayg12k9']' returned non-zero exit status 1.
(venv) myra@myra-ThinkPad-T14-Gen-2i:~/extra/autograder-server$ "

```

**Comment by james-perretta** [comment]
That usually means that the python3-dev package needs to be installed.
Could you try installing it for the version of python you're using? E.g.,
python3.10-dev

If that doesn't resolve it, could you follow up via email at
help@autograder.io? Thanks!
